site_name: stream-zip
repo_name: uktrade/stream-zip
repo_url: https://github.com/uktrade/stream-zip
theme:
  name: tech_docs_template
  logo: assets/dit-logo.png
  favicon: assets/dit-favicon.png
  features:
    - content.code.copy
    - navigation.sections
extra_css:
  - assets/dit-extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets
plugins:
  - material/search
nav:
  - Introduction: 'index.md'
  - Usage:
    - Getting started: 'getting-started.md'
    - Advanced usage: 'advanced-usage.md'
    - Limitations: 'limitations.md'
    - Recipes: 'recipes.md'
    - Exceptions: 'exceptions.md'

  - Contributing:
    - How to contribute: 'contributing.md'
